site_name: CM-Well
repo_url: https://github.com/CM-Well/CM-Well
#site_url: https://example.com/foo333/
site_description: CM-Well Documentation
site_author: CM-Well contibutors
#remote_branch
#remote_name
copyright: CM-Well copyright
#You want to set it to true after the documentation will stabilize (fails on warnings)
strict: true
#It's needed in order to create proper html links instead of directories. Only this way CM-Well can properly handle the links.
use_directory_urls: false
theme: 
  name: 'material'
  #logo: 'images/logo.svg' logo can be either image or icon!
  #favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true
  #font: false - to be complaint with GDPR (but will change the fonts. use custom template for the fonts section for that)
extra:
  social:
    - type: 'github'
      link: 'https://github.com/CM-Well/CM-Well'
#    - type: 'gitter'
#      link: 'https://gitter.im/CM-Well/CM-Well' - I couldn't get the gitter icon to be inversed colors
  search:
    tokenizer: '[\s]+'
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
plugins:
  - search:
      separator: '[\s]+'
nav:
  - Home:
    - index.md
    - License.md
    - Release Notes:
      - ReleaseNotes/ReleaseNotes.Atom.May.2019.md
      - ReleaseNotes/ReleaseNotes.Zebra2.February.2019.md
      - 2018:
        - ReleaseNotes/2018/ReleaseNotes.Piranha.January.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Quetzal.February.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Rhino.March.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Swan.April.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Turtle.May.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Unicorn.June.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Viper.June.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Wombat.August.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Xerus.October.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Yak.November.2018.md
        - ReleaseNotes/2018/ReleaseNotes.Zebra.December.2018.md
      - 2017:
        - ReleaseNotes/2017/ReleaseNotes.Amoeba.Feb.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Beowulf.Feb.2017.md
        - ReleaseNotes/2017/ReleaseNotes.CElegans.Mar.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Dolphin.Mar.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Firebird.May.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Gopher.May.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Hydra.June.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Iguana.July.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Jaguar.August.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Jan.17.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Jan.4.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Kingbird.September.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Lynx.September.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Mono.November.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Nautilus.November.2017.md
        - ReleaseNotes/2017/ReleaseNotes.Octopus.December.2017.md
      - 2016:
        - ReleaseNotes/2016/ReleaseNotes.Dec.15.2016.md
        - ReleaseNotes/2016/ReleaseNotes.Dec.7.2016.md
        - ReleaseNotes/2016/ReleaseNotes.Nov.10.2016.md
        - ReleaseNotes/2016/ReleaseNotes.Oct.6.2016.md
        - ReleaseNotes/2016/ReleaseNotes.Sept.11.2016.md    
  - Introduction:
    - Introduction/Intro.IntroductionToCM-Well.md
    - Introduction/Intro.CM-WellVsOtherInfoRepositories.md
    - Introduction/Intro.CM-WellDataParadigms.md
    - Introduction/Intro.OverviewOfTheCM-WellAPI.md
    - Introduction/Intro.TechnicalAspectsOfCM-Well.md
    - Introduction/Intro.CM-WellHigh-LevelArchitecture.md
    - Introduction/Intro.BriefHistoryOfCM-Well.md
    - Introduction/Intro.TechnicalDecisionsInCM-WellDesign.md
  - Developer Guide:
    - DeveloperGuide/DevGuide.NewToCM-Well.md
    - DeveloperGuide/DevGuide.QuickStart.md
    - DeveloperGuide/DevGuide.CurlUtility.md
    - DeveloperGuide/DevGuide.BasicQueries.md
    - DeveloperGuide/DevGuide.AdvancedQueries.md
    - DeveloperGuide/DevGuide.UpdatingCM-Well.md
    - DeveloperGuide/DevGuide.StreamingDataFromCM-Well.md
    - DeveloperGuide/DevGuide.SubscribingToReal-TimeUpdates.md
    - DeveloperGuide/DevGuide.UsingSPARQLOnCM-WellInfotons.md
    - DeveloperGuide/DevGuide.CallingJavaScalaFunctionsFromSPARQLQueries.md
    - DeveloperGuide/DevGuide.UsingElasticSearchStatistics.md
    - DeveloperGuide/DevGuide.WorkingWithNamedSub-Graphs.md  
    - DeveloperGuide/DevGuide.CM-WellSecurityFeatures.md
    - DeveloperGuide/DevGuide.ManagingUsers.md
    - DeveloperGuide/DevGuide.DosAndDonts.md
    - Best Practices:
      - DeveloperGuide/BestPractices/DevGuide.BestPractices.ConditionalUpdates.md
      - DeveloperGuide/BestPractices/DevGuide.BestPractices.DeletingKnownFieldValues.md
      - DeveloperGuide/BestPractices/DevGuide.BestPractices.ManagingRetries.md
      - DeveloperGuide/BestPractices/DevGuide.BestPractices.StreamingMethods.md
  - API Reference:
    - Authorization:
      - APIReference/Authorization/API.Auth.GeneratePassword.md
      - APIReference/Authorization/API.Auth.ChangePassword.md
      - APIReference/Authorization/API.Auth.InvalidateCache.md
      - APIReference/Authorization/API.Auth.Login.md
    - Get:
      - APIReference/Get/API.Get.GetSingleInfotonByURI.md
      - APIReference/Get/API.Get.GetSingleInfotonByUUID.md
      - APIReference/Get/API.Get.GetMultipleInfotonsByURI.md
    - Query:
      - APIReference/Query/API.Query.QueryForInfotonsUsingFieldConditions.md
      - APIReference/Query/API.Query.QueryForQuadsByTheirLabel.md
      - APIReference/Query/API.Query.ApplySPARQLToQueryResults.md
      - APIReference/Query/API.Query.ApplySPARQLToEntireGraph.md
      - APIReference/Query/API.Query.ApplyGremlinToQueryResults.md
      - APIReference/Query/API.Query.DataStatistics.md
    - Stream:
      - APIReference/Stream/API.Stream.CreateConsumer.md
      - APIReference/Stream/API.Stream.GetNextChunk.md
      - APIReference/Stream/API.Stream.ConsumeNextChunk.md
      - APIReference/Stream/API.Stream.ConsumeNextBulk.md
      - APIReference/Stream/API.Stream.CreateIterator.md
      - APIReference/Stream/API.Stream.StreamInfotons.md
    - Subscribe:
      - APIReference/Subscribe/API.Subscribe.SubscribeForPulledData.md
      - APIReference/Subscribe/API.Subscribe.PullNewData.md
      - APIReference/Subscribe/API.Subscribe.SubscribeForPushedData.md
      - APIReference/Subscribe/API.Subscribe.Unsubscribe.md
    - Traversal:
      - APIReference/Traversal/API.Traversal.Intro.md
      - APIReference/Traversal/API.Traversal.xg.md
      - APIReference/Traversal/API.Traversal.yg.md
      - APIReference/Traversal/API.Traversal.gqp.md
      - APIReference/Traversal/API.Traversal.Operands.md
    - Update:
      - APIReference/Update/API.Update.AddFileInfoton.md
      - APIReference/Update/API.Update.AddInfotonsAndFields.md
      - APIReference/Update/API.Update.AddInfotonsAndFieldsToSubGraph.md
      - APIReference/Update/API.Update.AddLinkInfoton.md
      - APIReference/Update/API.Update.DeleteASingleInfoton.md
      - APIReference/Update/API.Update.DeleteFields.md
      - APIReference/Update/API.Update.DeleteMultipleInfotons.md
      - APIReference/Update/API.Update.DeleteOrReplaceValuesInNamedSubGraph.md
      - APIReference/Update/API.Update.DeleteSpecificFieldValues.md
      - APIReference/Update/API.Update.Purge.md
      - APIReference/Update/API.Update.ReplaceFieldValues.md
      - APIReference/Update/API.Update.TrackUpdates.md
    - Usage Topics:
      - APIReference/UsageTopics/API.FieldConditionSyntax.md
      - APIReference/UsageTopics/API.FieldNameFormats.md
      - APIReference/UsageTopics/API.FromAndToDatetimeFormatting.md
      - APIReference/UsageTopics/API.InputAndOutputFormats.md
      - APIReference/UsageTopics/API.MetadataFields.md
      - APIReference/UsageTopics/API.PagingThroughResultsWithOffsetAndLengthParameters.md
      - APIReference/UsageTopics/API.ProtocolSystemField.md
      - APIReference/UsageTopics/API.QueryParameters.md
      - APIReference/UsageTopics/API.ReturnCodes.md
      - APIReference/UsageTopics/API.SortingResultsWithTheSort-byFlag.md
      - APIReference/UsageTopics/API.UsingConditionalUpdates.md
      - APIReference/UsageTopics/API.UsingTheBlockingFlag.md
      - APIReference/UsageTopics/API.UsingTheRecursiveFlag.md
      - APIReference/UsageTopics/API.UsingTheWith-dataFlag.md
      - APIReference/UsageTopics/API.UsingTheWith-deletedFlag.md
      - APIReference/UsageTopics/API.UsingTheWith-historyFlag.md
  - Tutorials:
    - Tutorials/Tutorial.Docker.md
    - Hands-On Exercises:
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.AddFileInfoton.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.AddInfotonsAndFields.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.DeleteInfotonsAndFields.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.GetInfotonsByURI.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.QueryForInfotons.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.QueryWithGremlin.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.QueryWithSPARQL.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.StreamWithIterator.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.StreamWithTheStreamOperation.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.SubscribeForPulledData.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.UpdateFields.md
      - Tutorials/HandsOnExercises/Tutorial.HandsOnExercises.WorkWithSubGraphs.md
  - Web Interface:
    - WebInterface/CM-WellWebInterface.md
    - WebInterface/CM-Well.OldWebInterface.md
  - Testing & Monitoring:
    - TestingAndMonitoring/Testing.TestingAndDebugging.md
    - TestingAndMonitoring/Monitoring.HealthDashboards.md
  - Advanced Topics:
    - Tools:
      - AdvancedTopics/Tools/Tools.UsingCM-WellDocker.md
      - AdvancedTopics/Tools/Tools.UsingTheCM-WellDownloader.md
      - AdvancedTopics/Tools/Tools.UsingTheCM-WellIngester.md
      - AdvancedTopics/Tools/Tools.UsingTheCM-WellSparkConnector.md
      - AdvancedTopics/Tools/Tools.UsingTheSPARQLTriggerProcessor.md
    - Building CM-Well: AdvancedTopics/Advanced.BuildingCM-Well.md
    - Cookbook: AdvancedTopics/Cookbook.CM-WellWithPermIDData.md
    - Admin:
      - AdvancedTopics/Admin/Admin.Backpressure.md
      - AdvancedTopics/Admin/Admin.Kafka.md
      - AdvancedTopics/Admin/Admin.TestAndFixCorruptedData.md
      - AdvancedTopics/Admin/Admin.DCC.md
    - Architecture:
      - AdvancedTopics/Architecture/Arch.Preface.md    
      - AdvancedTopics/Architecture/Arch.InfoArch.Part1.md
      - AdvancedTopics/Architecture/Arch.InfoArch.Infotons.md
      - AdvancedTopics/Architecture/Arch.InfoArch.InfoInMotion.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.Part1.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.DesignPrinciples.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.WebServiceAndGridStorage.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.BG.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.STP.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.ControlModules.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.ThirdPartyPackages.md
      - AdvancedTopics/Architecture/Arch.SoftwareArch.WebApplication.md
      - AdvancedTopics/Architecture/Arch.PlatformArch.Part1.md
      - AdvancedTopics/Architecture/Arch.PlatformArch.DCSync.md
      - AdvancedTopics/Architecture/Arch.Collaboration.md
  - Contact & Contribution: 
    - ContactAndContribution.md