#!/bin/sh
### BEGIN INIT INFO
# Provides:          cmwell-runner
# Required-Start:    \$remote_fs \$syslog
# Required-Stop:     \$remote_fs \$syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start cm-well at boot time
# Description:       Starts cm-well ctrl that starts cm-well processes.
### END INIT INFO

ctrl="/opt/cm-well/conf/ctrl/ctrl"

case "\$1" in
    start)
		while [ ! -f \$ctrl ]; do sleep 2; done
		\$ctrl start
    ;;
    stop)
		\$ctrl stop
    ;;
    restart)
		\$ctrl stop
		\$ctrl start
    ;;
    *)
    echo "Usage: \$0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
