#!/bin/sh
### BEGIN INIT INFO
# Provides:          ctrl
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

ctrl="/opt/cm-well/app/ctrl"
dc="/opt/cm-well/app/dc"
cmd="./start.sh"

name=`basename $0`
pid_file="/opt/cm-well/app/ctrl/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

case "$1" in
    start)
		export HAL=9000
		su {{user}} $ctrl/start.sh > /dev/null 2> /dev/null
		su {{user}} $dc/start.sh > /dev/null 2> /dev/null
    ;;
    stop)
		ps aux | grep ctrl | grep -v grep | grep -v starter | awk \'{print $2}\' | xargs -I zzz kill zzz
    ;;
    restart)
		$0 stop
		$0 start
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0