name: GRID

on: [pull_request]

jobs:
  test_GRID:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - continue-on-error: true
    - name: Run sbt test
      run: |
        echo pwd:
        pwd
        cd server
        ls -l .
        echo ooooooooooooooooo
        ls -l server/cmwell-grid
        echo aaaaaaaaaaaaa
        ls -l cmwell-grid
        echo ooooooooooooooooo
        echo pwd:
        pwd
        mkdir -p server/cmwell-grid/target/logs
        sbt grid/test
        echo pwd:
        echo pwd
        ls -l server/cmwell-grid/target/logs
        ls -l server/cmwell-grid/target
        ls -l server/cmwell-grid/
    - uses: actions/upload-artifact@master
      with:
        name: my-artifacts
        path: server/cmwell-grid/target/logs
