name: GRID

on: [pull_request]

jobs:
  test_GRID:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        echo pwd
        mkdir -p cmwell-grid/target/logs
        sbt grid/test
        echo pwd
        ll cmwell-grid/target/logs
    - uses: actions/upload-artifact@master
      with:
        name: my-artifacts
        path: server/cmwell-grid/target/logs
