name: IT

on: [pull_request]

jobs:
  test_it:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install Scala
      working-directory: server
      run: pwd
    - name: Checking directory
      run: pwd
