name: IT

on: [pull_request]

jobs:
  test_it:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run sbt test
      run: |
        wget https://downloads.lightbend.com/scala/2.12.8/scala-2.12.8.tgz
        sudo echo $PATH
        sudo tar -xf scala-2.12.8.tgz --directory=/usr/local/bin
        sudo ls /usr/local/bin
        scala -version
        python --version
        cd server
        sbt it:testOnly cmwell.it.QuadTests
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: logs
        path: server/cmwell-it/target/logs
    
