name: MacCiCd

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
##################################
##    Running all unit tests    ##
##################################
  unitTests:
    runs-on: macos-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Some command
        run: |
          ls
          pwd
