name: CI

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt compile
      run: |
        echo pwd
        cd server
        sbt util/compile
        sbt kafkaAssigner/compile
        
  test_1:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo this is one line
    - name: Run sbt compile
      run: |
        echo pwd
        cd server
        sbt util/test
        sbt kafkaAssigner/test
        sbt dao/test
        sbt domain/test

  test_2:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo this is one line
    - name: Run sbt compile
      run: |
        echo pwd
        cd server
        sbt zstore/test
        sbt common/test
  
