name: CI

on: [pull_request]

jobs:
  unitTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: |
          echo pwd
          cd server
          sbt compile
          
      - name: Test
        run: |
          cd server
          sbt test
      - name: Save logs
        if: always()
        run: |
          mkdir logsArtifacts
          find . -name logs | xargs -I LOG cp -r --parents LOG logsArtifacts/
          
###  Save Artifacts                    
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: logsArtifacts
          path: logsArtifacts
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: client1.out
          path: server/cmwell-grid/target/client1.out
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: client2.out
          path: server/cmwell-grid/target/client2.out
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: node.out
          path: server/cmwell-grid/target/node.out
       
  integrationTests:
    runs-on: ubuntu-latest
#    needs: unitTests

    steps:
    - uses: actions/checkout@v1
    - name: Install Scala
      run: |
        wget https://downloads.lightbend.com/scala/2.12.8/scala-2.12.8.tgz
        sudo tar -xf scala-2.12.8.tgz
        sudo ln -s `pwd`/scala-2.12.8/bin/scala /usr/local/bin/scala
    - name: Test
      run: |
        cd server
        sbt it:test
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: itLogs
        path: server/cmwell-it/target/logs

    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: cmwellItLogs
        path: server/cmwell-it/target/cm-well/log
