name: CI

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: |
          echo pwd
          cd server
          sbt compile

# Took 2:43 instead of 1:01 at the other version! 
##      - name: Run sbt test - version1
##        run: |
##          echo pwd
##          cd server
##          sbt util/test
##          sbt kafkaAssigner/test
##          sbt dao/test
#          sbt domain/test

      - name: Test util, kafkaAssigner, dao, domain
        run: |
          echo pwd
          cd server
          sbt util/test kafkaAssigner/test dao/test domain/test
          
      - name: Test zstore, common, grid
        run: |
          echo pwd
          cd server
          sbt zstore/test common/test grid/test

      - name: Test rts fts
        if: always()
        run: |
          echo pwd
          cd server
          sbt rts/test fts/test

      - name: Test format irw stortill
        if: job.steps.Compile.status == success()
        run: |
          echo pwd
          cd server
          sbt formats/test irw/test stortill/test          

      - name: Test ctrl dc cons pluginGremlin
        run: |
          echo pwd
          cd server
          sbt ctrl/test dc/test cons/test pluginGremlin/test

      - name: Test spa dataTools dataToolsApp
        run: |
          echo pwd
          cd server
          sbt spa/test dataTools/test dataToolsApp/test

      - name: Test sparqlAgent tracking ws
        run: |
          echo pwd
          cd server
          sbt sparqlAgent/test tracking/test ws/test
        
  test_bg:

    runs-on: ubuntu-latest
    needs: compile

    steps:
      - uses: actions/checkout@v1
      - name: Run sbt test
        run: |
          echo pwd
          cd server
          sbt bg/test

  test_it:

    runs-on: ubuntu-latest
    needs: compile

    steps:
      - uses: actions/checkout@v1
      - name: Run sbt test
        run: |
          echo pwd
          cd server
          sbt consIt/test
          
###  Save Artifacts          
          
      - uses: actions/upload-artifact@master
        with:
          name: my-artifacts
          path: cmwell-grid/target/logs
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: application.log
          path: server/cmwell-grid/target/logs/application.log
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: client1.out
          path: server/cmwell-grid/target/client1.out
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: client2.out
          path: server/cmwell-grid/target/client2.out
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: node.out
          path: server/cmwell-grid/target/node.out


