name: CI

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt compile
      run: |
        echo pwd
        cd server
        sbt compile
        
  test_1:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt util/test
        sbt kafkaAssigner/test
        sbt dao/test
        sbt domain/test

  test_2:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt zstore/test
        sbt common/test
    - uses: actions/upload-artifact@master
      with:
        name: my-artifacts
        path: **/target/**/logs/*
  
  test_3_FAIL:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt grid/test
        sbt rts/test
        sbt fts/test

  test_4:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt formats/test
        sbt irw/test
        sbt stortill/test
        
  test_bg:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt bg/test

  test_it:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt consIt/test
        
  test_6:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt ctrl/test
        sbt dc/test
        sbt cons/test
        sbt pluginGremlin/test
        
  test_7:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt spa/test
        sbt dataTools/test
        sbt dataToolsApp/test
   
  test_8:

    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sbt test
      run: |
        echo pwd
        cd server
        sbt sparqlAgent/test
        sbt tracking/test
        sbt ws/test
